### ISSUE TITLE
qpe segfault under qvfb if no bluetooth adapter is found

### ISSUE THREAD

**Issue by ydirson** [radekp/qtmoko#63]
This is rev 8b695ee46 on debian/testing/amd64 in qvfb mode. Launching runqtopia, qpe quickly bombs out after displaying the desktop as follows.  If I plug a bluetooth USB dongle, it starts up more properly.

QtopiaServer :  ApplicationLauncher::handleStateChanged( "qdsync" ,  "Starting" )
QDBusObjectPath: invalid path ""
Method call  "/->DefaultAdapter()"  failed:  QDBusError("org.bluez.Error.NoSuchAdapter", "No such adapter")

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff449fdf8 in QDBusAbstractInterface::d_func (this=0x0) at /work/yann/freerunner/qtmoko/qtmoko/qtopiacore/qt/src/dbus/qdbusabstractinterface.h:138
138         Q_DECLARE_PRIVATE(QDBusAbstractInterface)
(gdb) Did not receive a connection event from the qws server
Did not receive a connection event from the qws server
Did not receive a connection event from the qws server
Did not receive a connection event from the qws server
Did not receive a connection event from the qws server
bt
#0  0x00007ffff449fdf8 in QDBusAbstractInterface::d_func (this=0x0) at /work/yann/freerunner/qtmoko/qtmoko/qtopiacore/qt/src/dbus/qdbusabstractinterface.h:138
#1  0x00007ffff449ebfe in QDBusAbstractInterface::isValid (this=0x0) at /work/yann/freerunner/qtmoko/qtmoko/qtopiacore/qt/src/dbus/qdbusabstractinterface.cpp:303
#2  0x00007ffff67854c7 in QBluetoothDbusIface::btcall<unsigned int> (this=0x0, method=..., reply=..., args=..., async=false, receiver=0x0, returnMethod=0x0, errorMethod=0x0)

```
at /work/yann/freerunner/qtmoko/build-test/sdk/include/qtopiacomm/qbluetoothdbus.h:92
```
#3  0x00007ffff6783a71 in QBluetoothAbstractServicePrivate::registerRecord (this=0xb626b0, record=...)

```
at /work/yann/freerunner/qtmoko/qtmoko/src/libraries/qtopiacomm/bluetooth/qbluetoothabstractservice.cpp:273
```
#4  0x00007ffff67848c1 in QBluetoothAbstractService::registerRecord (this=0xb72030, record=...)

```
at /work/yann/freerunner/qtmoko/qtmoko/src/libraries/qtopiacomm/bluetooth/qbluetoothabstractservice.cpp:426
```
#5  0x0000000000639f97 in QBluetoothHandsfreeService::start (this=0xb72030) at /work/yann/freerunner/qtmoko/qtmoko/src/server/bluetooth/hf/qbluetoothhfservice.cpp:255
#6  0x00007ffff678231e in Messenger::startService (this=0xb62710, name=...) at /work/yann/freerunner/qtmoko/qtmoko/src/libraries/qtopiacomm/bluetooth/qbluetoothabstractservice.cpp:93
#7  0x00007ffff67850e8 in Messenger::qt_metacall (this=0xb62710, _c=QMetaObject::InvokeMetaMethod, _id=3, _a=0x7fffffffce80)

```
at /work/yann/freerunner/qtmoko/build-test/src/libraries/qtopiacomm/.moc/qbluetoothabstractservice.moc:87
```
#8  0x00007ffff57642ba in QSlotInvoker::invoke (this=0xb63ab0, args=...) at /work/yann/freerunner/qtmoko/qtmoko/src/libraries/qtopiabase/qslotinvoker.cpp:225
#9  0x00007ffff5771672 in QtopiaIpcAdaptor::received (this=0xb62710, msg=..., data=...) at /work/yann/freerunner/qtmoko/qtmoko/src/libraries/qtopiabase/qtopiaipcadaptor.cpp:579
#10 0x00007ffff57703b8 in QtopiaIpcAdaptorChannel::receive (this=0xb62960, msg=..., data=...) at /work/yann/freerunner/qtmoko/qtmoko/src/libraries/qtopiabase/qtopiaipcadaptor.cpp:157
#11 0x00007ffff32b92d2 in QCopChannel::sendLocally (ch=..., msg=..., data=...) at /work/yann/freerunner/qtmoko/qtmoko/qtopiacore/qt/src/gui/embedded/qcopchannel_qws.cpp:600
#12 0x00007ffff336c17a in QApplication::qwsProcessEvent (this=0xa9bbd0, event=0x113bea0) at /work/yann/freerunner/qtmoko/qtmoko/qtopiacore/qt/src/gui/kernel/qapplication_qws.cpp:2721
#13 0x00007ffff33733ee in QEventDispatcherQWS::processEvents (this=0xa962a0, flags=...) at /work/yann/freerunner/qtmoko/qtmoko/qtopiacore/qt/src/gui/kernel/qeventdispatcher_qws.cpp:119
#14 0x00007ffff2a412a4 in QEventLoop::processEvents (this=0x7fffffffd760, flags=...) at /work/yann/freerunner/qtmoko/qtmoko/qtopiacore/qt/src/corelib/kernel/qeventloop.cpp:149
#15 0x00007ffff2a413f8 in QEventLoop::exec (this=0x7fffffffd760, flags=...) at /work/yann/freerunner/qtmoko/qtmoko/qtopiacore/qt/src/corelib/kernel/qeventloop.cpp:197
#16 0x00007ffff2a436ac in QCoreApplication::exec () at /work/yann/freerunner/qtmoko/qtmoko/qtopiacore/qt/src/corelib/kernel/qcoreapplication.cpp:888
#17 0x00007ffff3310fef in QApplication::exec () at /work/yann/freerunner/qtmoko/qtmoko/qtopiacore/qt/src/gui/kernel/qapplication.cpp:3525
#18 0x00007ffff5ada363 in QtopiaApplication::exec (this=0xa9bbd0) at /work/yann/freerunner/qtmoko/qtmoko/src/libraries/qtopia/qtopiaapplication.cpp:4126
#19 0x00000000005aa845 in initApplication (argc=1, argv=0x7fffffffdc28) at /work/yann/freerunner/qtmoko/qtmoko/src/server/main/main.cpp:461
#20 0x00000000005ab712 in main (argc=1, argv=0x7fffffffdc28) at /work/yann/freerunner/qtmoko/qtmoko/src/server/main/main.cpp:558

**Comment by radekp** [comment]
There is something working in the bluetooth dbus code when bluetooth adapter does not exit. You can workaround this by compiling without bluetooth (there is configure switch for it).

Bluetooth was my first playing with dbus. It has to be rewritten to use qdbusxml2cpp same way as ofono and fso bindings are done. It should be quite easy to do it.
